server:
  port: ${GATEWAY_PORT}

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: my-service
              uri: http://google.com
              predicates:
                - Path=/**


api:
  security:
    token:
      secret: ${TOKEN_SECRET}
      issuer: mtg-trade