server:
  port: ${GATEWAY_PORT}

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: gateway

api:
  security:
    token:
      secret: ${TOKEN_SECRET}
      issuer: mtg-trade
